name: customer_cracktreck
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  sms_autofill: ^2.4.0
  image_picker: ^1.2.1
  provider: ^6.0.5
  country_state_city_picker: ^1.2.8
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assests/Bio_metric.png
    - assests/cctv.png
    - assests/computer.png
    - assests/epbx.png
    - assests/laptop.png
    - assests/printer.png
    - assests/router.png
    - assests/server.png
    - assests/banner_1.jpg
    - assests/banner_2.png
